# Generated by Django 2.0 on 2018-12-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kernel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichier',
            options={'ordering': ['date'], 'verbose_name': 'fichier'},
        ),
        migrations.AddField(
            model_name='fichier',
            name='abscisse',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='ordonnee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
