# Generated by Django 2.0 on 2018-12-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kernel', '0002_auto_20181225_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='abscisse',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='ordonnee',
        ),
    ]
