# Generated by Django 2.0 on 2018-12-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kernel', '0003_auto_20181225_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='absc_data',
            field=models.CharField(default=0, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='ord_data',
            field=models.CharField(default=0, max_length=20000),
            preserve_default=False,
        ),
    ]
